# Notebook-test
## First: 
This is my first time using a notebook and ill be learning basics of tensorflow and keras...

## Test call :

In [8]:
list = [12,13,15,14,17]
sorted(list)

[12, 13, 14, 15, 17]

# Constant tensos and veriables: 
## All-ones and All-zeros tensors:

In [5]:
import tensorflow as tf 

x = tf.ones(shape=(2,1)) #same as np.ones(shape=(2,1))
print(x)

y = tf.zeros(shape=(3,1)) #same as np.zeros(shape=(3,1))
print(y)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]], shape=(3, 1), dtype=float32)


## Random tensors from distributions:

In [6]:
x = tf.random.normal(shape=(3,1),mean=0,stddev=1) #same as np.random.normal(shape=(3,1),loc=0,scale=1)
print(x)

y = tf.random.uniform(shape=(3,1),minval=0,maxval=5) #same as np.random.uniform(shape=(3,1),low=0,high=5)
print(y)

tf.Tensor(
[[ 0.5867173 ]
 [-1.1266687 ]
 [ 0.00646758]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[4.8187943 ]
 [0.86198807]
 [1.459927  ]], shape=(3, 1), dtype=float32)


A difference between numpy arrays and tensorflow tensors is that TF tensors are not assignable 
In numpy u can do:
x = np.ones(shape(2,2))
x[0,0] = 0 
But in TF u cant do the same, it will fail as tensor isn't assignable thats where tf *Variables* come in
## TF Veriables:

In [31]:
#To create a variable, you need to provide some initial value, such as a random tensor.
v = tf.Variable(initial_value = tf.random.normal(shape=(3,1)))
print(v)

v.assign(tf.ones((3,1))) #assigning a value to TF Variable
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.07280061],
       [ 0.7614509 ],
       [-0.36306515]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [32]:
#also works for subset of tf variable 
v[0,0].assign(3)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [34]:
#assign_add() and assign_sub() are equivalent to += and -=
v.assign_add(tf.ones((3,1)))
print(v)
v.assign_sub(tf.ones((3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


# Tensor Operations:
## A few basic math operations:

In [ ]:
a = tf.ones(2,1)
b = tf.square(a) #takes the square
c = tf.sqrt(a) #takes the sqrt
d = b + c #addition similarly substraction too can be performed 
e = tf.matmul(d,b) #dot product
e *= d #element wise multiplication

# GradientTape
Retrieve the gradient of any differentiable expression with respect to any of its
inputs.
## Using GradientTape:

In [46]:
input_var = tf.Variable(3.0)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result,input_var)
print(result)
print(gradient)

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


##  Using nested gradient tapes to compute second-order graients:
assume time as a veriable, and also assume that
* position(time) = 4.9 * time**2
* therefore speed = gradient of position wrt time 
* and acceleration = gradient of speed wrt time

In [49]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position,time)
acceleration = outer_tape.gradient(speed,time)

print(position)
print(speed)
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(9.8, shape=(), dtype=float32)


The gradient is calculated outside the tape instance, the tape instance is to keep watch on the function for whoch the gradient is to be calculated (my understanding).

> This marks the end of the my first notebook which was dedicated to learning about how to define tensors, perform basic tensor operations and how to calculate the gradients under GradientTape instances.